### PR TITLE
use Terraform and provider version as packngo UserAgent

### LINKED ISSUE #19: User-Agent does not report Terraform
This has come up before and was thought to be corrected, but it is clear that the User-Agent being reported is currently incorrect. The reported User-Agent is not being set (https://github.com/equinix/terraform-provider-metal/blob/main/metal/config.go#L61).

```sh
TF_LOG=debug PACKNGO_DEBUG=1 terraform apply
```

```
terraform-provider-metal_v1.0.0: ---[ REQUEST ]---------------------------------------
2021-01-28T17:10:39.216-0500 [DEBUG] plugin.terraform-provider-metal_v1.0.0: POST /metal/v1/projects/.../ssh-keys HTTP/1.1
2021-01-28T17:10:39.216-0500 [DEBUG] plugin.terraform-provider-metal_v1.0.0: Host: api.equinix.com
2021-01-28T17:10:39.216-0500 [DEBUG] plugin.terraform-provider-metal_v1.0.0: User-Agent: packngo/0.5.1
2021-01-28T17:10:39.216-0500 [DEBUG] plugin.terraform-provider-metal_v1.0.0: Connection: close
2021-01-28T17:10:39.216-0500 [DEBUG] plugin.terraform-provider-metal_v1.0.0: Content-Length: 769
2021-01-28T17:10:39.216-0500 [DEBUG] plugin.terraform-provider-metal_v1.0.0: Accept: application/json
2021-01-28T17:10:39.216-0500 [DEBUG] plugin.terraform-provider-metal_v1.0.0: Content-Type: application/json
2021-01-28T17:10:39.216-0500 [DEBUG] plugin.terraform-provider-metal_v1.0.0: X-Auth-Token: ...
2021-01-28T17:10:39.216-0500 [DEBUG] plugin.terraform-provider-metal_v1.0.0: X-Consumer-Token: aZ9GmqHTPtxevv
```

### PR DESCRIPTION
**Pull request by displague**
Fixes #19 

When tested locally using `TF_LOG=DEBUG TF_ACC=1 go test ./... -v -timeout=20m -run=TestAcc...`:

```
User-Agent: HashiCorp Terraform/0.11+compatible (+https://www.terraform.io) Terraform Plugin SDK/1.0.0 terraform-provider-metal/dev
```

### CODE REVIEW

File: metal/config.go [hunk 1]
```diff
@@ -59,5 +64,13 @@ func (c *Config) Client() *packngo.Client {
 	retryClient.RetryWaitMax = c.MaxRetryWait
 	retryClient.CheckRetry = packngo.RetryPolicy
 	httpClient := retryClient.StandardClient()
-	return packngo.NewClientWithAuth(consumerToken, c.AuthToken, httpClient)
+
+	client := packngo.NewClientWithAuth(consumerToken, c.AuthToken, httpClient)
+	tfUserAgent := httpclient.TerraformUserAgent(c.terraformVersion)
```
Comment (displague) [inline metal/config.go:69]: https://www.terraform.io/docs/extend/guides/v1-upgrade-guide.html#deprecations suggested this function exists for the v2 SDK, it appears to be in the (unversioned) v1 SDK, identical to what we had. Looks like we don't have to duplicate it.

See 9692ab0

**Review by displague — COMMENTED** [review]
> Maybe we can also later add used packngo version, if we make the libraryVersion in packngo exported, i.e. rename to LibraryVersion.

Added. Packngo exports this via `Client.UserAgent`.

It would be handy to have the Version number available without grabbing the UserAgent.

**Comment by displague** [comment]
Another easy way to test this PR is to run any test with an invalid token:

`PACKET_AUTH_TOKEN=foo TF_LOG=DEBUG TF_ACC=1 go test ./... -v -timeout=20m -run=TestAccMetalDataSourceProject_Basic`

```
---[ REQUEST ]---------------------------------------
POST /metal/v1/organizations HTTP/1.1
Host: api.equinix.com
User-Agent: HashiCorp Terraform/0.11+compatible (+https://www.terraform.io) Terraform Plugin SDK/1.0.0 terraform-provider-metal/dev packngo/0.6.0
Connection: close
Content-Length: 96
Accept: application/json
Content-Type: application/json
X-Auth-Token: foo
X-Consumer-Token: aZ9GmqHTPtxevvFq9SK3Pi2yr9YCbRzduCSXF2SNem5sjB91mDq7Th3ZwTtRqMWZ
Accept-Encoding: gzip

{
 "name": "tfacc-organization-cd04827da4fa",
 "description": "",
 "website": "",
 "twitter": "",
 "logo": ""
}
```

File: .goreleaser.yml [hunk 2]
```diff
@@ -14,7 +14,7 @@ builds:
   flags:
     - -trimpath
   ldflags:
-    - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
+    - -s -w -X version.ProviderVersion={{.Version}}
```
Comment (displague) [inline .goreleaser.yml:17]: compare to https://github.com/hashicorp/terraform-provider-aws/search?q=ProviderVersion

We do not have a main.version or main.commit variable defined. We do now have a version.ProviderVersion.

File: metal/config.go [hunk 3]
```diff
@@ -59,5 +64,13 @@ func (c *Config) Client() *packngo.Client {
 	retryClient.RetryWaitMax = c.MaxRetryWait
 	retryClient.CheckRetry = packngo.RetryPolicy
 	httpClient := retryClient.StandardClient()
```
Comment (t0mk) [inline metal/config.go:66]: can we rename the variable httpClient to "standardClient" so that it's doesn't clash with package "github.com/hashicorp/terraform-plugin-sdk/httpclient", it's a bit confusing to read

File: metal/config.go (hunk 1 above)
Comment (t0mk) [reply metal/config.go:69]: :+1:

File: .goreleaser.yml (hunk 2 above)
Comment (t0mk) [reply .goreleaser.yml:17]: :+1:

**Review by t0mk — APPROVED** [review]
UserAgent for an acceptance test was

```
User-Agent: HashiCorp Terraform/0.11+compatible (+https://www.terraform.io) 
Terraform Plugin SDK/1.0.0 terraform-provider-metal/dev packngo/0.6.0
```
(on one line)

File: metal/config.go (hunk 3 above)
Comment (displague) [reply metal/config.go:66]: logging this as https://github.com/equinix/terraform-provider-metal/issues/39 and merging
